"""empty message

Revision ID: 12ada3257660
Revises: 76939fd9d1ee
Create Date: 2022-08-19 00:48:42.893446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ada3257660'
down_revision = '76939fd9d1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'address', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='unique')
    # ### end Alembic commands ###
