"""empty message

Revision ID: 94fabac9f7d2
Revises: 0eaf67bb6a44
Create Date: 2022-08-16 21:34:05.456837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fabac9f7d2'
down_revision = '0eaf67bb6a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'date_created')
    # ### end Alembic commands ###
